kind: PersistentVolume
apiVersion: v1
metadata:
  name: consul-server-0-pv
  labels:
    app: postgres
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data"